config_name: config

defaults:
  - default_features

data:
    file_reader: tfxkit.common.base_utils.read_csv
    labels:
    - target
    train_weights_column: null
    xy_maker: tfxkit.common.tf_utils.xy_maker
evaluation:
    args: null
    variable: pred
logging:
    level: DEBUG
model:
    function: tfxkit.common.tf_utils.define_mlp
    overwrite: false
    reload_model: true
optimizer:
    function: keras.optimizers.AdamW
    loss: binary_crossentropy
    metrics:
    - accuracy
    parameters:
        clipnorm: 1.0
        ema_momentum: 0.999
        ema_overwrite_frequency: true
        learning_rate: 0.001
        weight_decay: 0.0005
plotter:
    functions:
        plot_history:
            function: plot_history
        plot_predictions:
            function: plot_predictions
            parameters:
                plot_name: Preds
                weight_column_train:
                - 0.2
                weight_column: null
                x_label: My Predictions
                comparison: 'ratio'
    plots_path: plots
    sequence:
    - plot_history
    - plot_predictions
    - plot_roc
save_dir: save_dir
tasks:
- train
training:
    batch_size: 32
    class_weight: null
    epochs: 10
    initial_epoch: 0
    shuffle: true
    steps_per_epoch: null
    validation_batch_size: null
    validation_data: null
    validation_freq: 1
    validation_split: 0.2
    validation_steps: null
tuner:
    functions:
        generic_tuner:
            function: tfxkit.core.tuner.generic_tuner
    search:
        batch_size: 86000
        validation_split: 0.2
    sequence:
    - generic_tuner
    tuner:
        function: keras_tuner.BayesianOptimization
        parameters:
            alpha: 0.0001
            beta: 2.6
            directory: tuner_dir
            executions_per_trial: 2
            max_trials: 100
            objective: val_loss
            overwrite: false
            project_name: HPTunning
